export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST'
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS'
export const FETCH_GAMES_FAILURE = 'FETCH_GAMES_FAILURE'

export const FETCH_GAME_REQUEST = 'FETCH_GAME_REQUEST'
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS'
export const FETCH_GAME_FAILURE = 'FETCH_GAME_FAILURE'

export const UPDATE_GAME_REQUEST = 'UPDATE_GAME_REQUEST'
export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS'
export const UPDATE_GAME_FAILURE = 'UPDATE_GAME_FAILURE'
