export const FETCH_PLACES_REQUEST = 'FETCH_PLACES_REQUEST'
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS'
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE'

export const CREATE_PLACE_REQUEST = 'CREATE_PLACE_REQUEST'
export const CREATE_PLACE_SUCCESS = 'CREATE_PLACE_SUCCESS'
export const CREATE_PLACE_FAILURE = 'CREATE_PLACE_FAILURE'

export const DELETE_PLACE_REQUEST = 'DELETE_PLACE_REQUEST'
export const DELETE_PLACE_SUCCESS = 'DELETE_PLACE_SUCCESS'
export const DELETE_PLACE_FAILURE = 'DELETE_PLACE_FAILURE'
