export const CREATE_WAYPOINT_REQUEST = 'CREATE_WAYPOINT_REQUEST'
export const CREATE_WAYPOINT_SUCCESS = 'CREATE_WAYPOINT_SUCCESS'
export const CREATE_WAYPOINT_FAILURE = 'CREATE_WAYPOINT_FAILURE'

export const DELETE_WAYPOINT_REQUEST = 'DELETE_WAYPOINT_REQUEST'
export const DELETE_WAYPOINT_SUCCESS = 'DELETE_WAYPOINT_SUCCESS'
export const DELETE_WAYPOINT_FAILURE = 'DELETE_WAYPOINT_FAILURE'
